Config.Locations = {

    ["mcdonalds"] = {
        ["label"] = "McDonalds",
        ["coords"] = vector4(90.56, 285.77, 110.22, 69.58),
        ["ped"] = 'a_m_y_beach_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-leaf",
        ["targetLabel"] = "Order McDonalds",
        ["products"] = Config.Products["mcdonalds"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(90.56, 285.77, 110.22, 69.58)
    },
}


Config.Products = {
    ["mcdonalds"] = {
        [1] = {
            name = 'bigmac',
            price = 50,
            amount = 50,
            info = {},
            type = 'item',
            slot = 1,
        },
        [2] = {
            name = 'mcchicken',
            price = 50,
            amount = 50,
            info = {},
            type = 'item',
            slot = 2,
        },
        [3] = {
            name = 'quarterpounder',
            price = 50,
            amount = 50,
            info = {},
            type = 'item',
            slot = 3,
        },
        [4] = {
            name = 'dquarterpounder',
            price = 50,
            amount = 50,
            info = {},
            type = 'item',
            slot = 4,
        },
        [5] = {
            name = 'filet-o-fish',
            price = 50,
            amount = 50,
            info = {},
            type = 'item',
            slot = 5,
        },
        [6] = {
            name = 'bigmac_meal',
            price = 50,
            amount = 150,
            info = {},
            type = 'item',
            slot = 6,
        },
        [7] = {
            name = 'mcchicken_meal',
            price = 50,
            amount = 150,
            info = {},
            type = 'item',
            slot = 7,
        },
        [8] = {
            name = 'quarterpounder_meal',
            price = 50,
            amount = 150,
            info = {},
            type = 'item',
            slot = 8,
        },
        [9] = {
            name = 'dquarterpounder_meal',
            price = 50,
            amount = 150,
            info = {},
            type = 'item',
            slot = 9,
        },
        [10] = {
            name = 'filet-o-fish_meal',
            price = 50,
            amount = 150,
            info = {},
            type = 'item',
            slot = 10,
        },
        [11] = {
            name = 'cheeseburger',
            price = 50,
            amount = 50,
            info = {},
            type = 'item',
            slot = 11,
        },
        [12] = {
            name = 'dcheeseburger',
            price = 50,
            amount = 50,
            info = {},
            type = 'item',
            slot = 12,
        },
        [13] = {
            name = 'tcheeseburger',
            price = 50,
            amount = 50,
            info = {},
            type = 'item',
            slot = 13,
        },
        [14] = {
            name = 'sfries',
            price = 50,
            amount = 30,
            info = {},
            type = 'item',
            slot = 14,
        },
        [15] = {
            name = 'mfries',
            price = 50,
            amount = 50,
            info = {},
            type = 'item',
            slot = 15,
        },
        [16] = {
            name = 'cheeseburger_meal',
            price = 50,
            amount = 150,
            info = {},
            type = 'item',
            slot = 16,
        },
        [17] = {
            name = 'dcheeseburger_meal',
            price = 50,
            amount = 150,
            info = {},
            type = 'item',
            slot = 17,
        },
        [18] = {
            name = 'tcheeseburger_meal',
            price = 50,
            amount = 150,
            info = {},
            type = 'item',
            slot = 18,
        },
        [19] = {
            name = 'lfries',
            price = 50,
            amount = 70,
            info = {},
            type = 'item',
            slot = 19,
        },
        [20] = {
            name = 'cocacola',
            price = 50,
            amount = 50,
            info = {},
            type = 'item',
            slot = 20,
        },
        [21] = {
            name = '6pnuggets',
            price = 50,
            amount = 50,
            info = {},
            type = 'item',
            slot = 21,
        },
        [22] = {
            name = '10pnuggets',
            price = 50,
            amount = 50,
            info = {},
            type = 'item',
            slot = 22,
        },
        [23] = {
            name = '20pnuggets',
            price = 50,
            amount = 50,
            info = {},
            type = 'item',
            slot = 23,
        },
        [24] = {
            name = 'sscone',
            price = 50,
            amount = 20,
            info = {},
            type = 'item',
            slot = 24,
        },
        [25] = {
            name = 'ssconef',
            price = 50,
            amount = 20,
            info = {},
            type = 'item',
            slot = 25,
        },
        [26] = {
            name = '6pnuggets_meal',
            price = 50,
            amount = 150,
            info = {},
            type = 'item',
            slot = 26,
        },
        [27] = {
            name = '10pnuggets_meal',
            price = 50,
            amount = 150,
            info = {},
            type = 'item',
            slot = 27,
        },
        [28] = {
            name = '20pnuggets_meal',
            price = 50,
            amount = 150,
            info = {},
            type = 'item',
            slot = 28,
        },
        [29] = {
            name = 'mflurryo',
            price = 50,
            amount = 50,
            info = {},
            type = 'item',
            slot = 29,
        },
        [30] = {
            name = 'mflurrym',
            price = 50,
            amount = 50,
            info = {},
            type = 'item',
            slot = 30,
        },
        [31] = {
            name = 'hotapplepie',
            price = 50,
            amount = 20,
            info = {},
            type = 'item',
            slot = 31,
        },
    },
